
exclude:
  - "/vendor/"
  - "Gemfile"
  - "Gemfile.lock"
  - "README.md"
  - "LICENSE.md"
  - "*.gemspec"
  - "*.sh"
  - "/notes/"

keep_files:
  - "CNAME"
  - ".git"
  - ".gitignore"


# Site settings
title: Shalom Boroda
subtitle: "Technical and marketing content"
url: "" # the base hostname & protocol for your site
baseurl: "" # Set this value to "" if you want your site to be root
#cover: "/assets/cover.png"
#logo: "/assets/logo.png"

# Build settings
markdown: kramdown

# Google analytics
# ga_tracking_id: "UA-XXXX-1"

# Category descriptions (for archive pages)
descriptions:
  - cat: jekyll
    desc: "Posts describing Jekyll setup techniques."

  - cat: dummy
    desc: "Just some placeholder posts, lorem ipsum and the rest."
